package fr.ecurie_du_loup.generique_util.service;

import fr.ecurie_du_loup.generique_util.data.ObjectTestSample;

public class ObjectTestSampleDataBaseServiceWithDaoUtilAndLongIdImpl extends DataBaseServiceWithDaoIdLongUtilAndLongId<ObjectTestSample> implements ObjectTestSampleDataBaseServiceWithDaoUtilAndLongId{

}
